table fOrcadoProjecao
	lineageTag: 976668cf-19de-4a6d-9fa3-3378f9f33f02

	column COD_CASA
		dataType: string
		lineageTag: 4897a665-022c-4b1e-b8d7-d8dc8c5e0612
		summarizeBy: none
		sourceColumn: COD_CASA

		annotation SummarizationSetBy = Automatic

	column COD_CENTRO_CUSTO
		dataType: string
		lineageTag: 006fdaff-a29f-45df-95bb-ca4e84e82899
		summarizeBy: none
		sourceColumn: COD_CENTRO_CUSTO

		annotation SummarizationSetBy = Automatic

	column CONTA_CONTABIL
		dataType: string
		lineageTag: 1d8d3797-d8fd-4c30-a1f6-6587036c58eb
		summarizeBy: none
		sourceColumn: CONTA_CONTABIL

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: d55a5216-7d94-4a76-955d-3575c2b4fa0d
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VALOR
		dataType: double
		lineageTag: 91a55a80-7c90-4429-b710-2e88069f80ad
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fOrcadoProjecao = m
		mode: import
		source =
				let
				    Fonte = Folder.Files("\\192.168.0.8\Sys1\Home\BiPowerBI\PB Lopes\Resultado Gerencial\Orçado Projeção"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo (5)", each #"Transformar Arquivo (5)"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo (5)"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo (5)", Table.ColumnNames(#"Transformar Arquivo (5)"(#"Arquivo de Amostra (5)"))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Coluna de Tabela Expandida1",{{"Nome da Origem", type text}, {"COD_CASA", type text}, {"COD_CENTRO_CUSTO", type text}, {"CONTA CONTABIL", type text}, {"DATA", type date}, {"VALOR", type number}, {"GRUPO", type text}, {"GRUPO_DRE", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"CONTA CONTABIL", "CONTA_CONTABIL"}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Renomeadas",{"COD_CASA", "COD_CENTRO_CUSTO", "CONTA_CONTABIL", "DATA", "VALOR"})
				in
				    #"Outras Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

