table fOrcProjecaoFinEstorno500
	lineageTag: 6368b04d-60b1-4dfb-b29e-992595ed1843

	column COD_CASA
		dataType: string
		lineageTag: 22277304-c19a-4a13-8820-5ddca5dbd696
		summarizeBy: none
		sourceColumn: COD_CASA

		annotation SummarizationSetBy = Automatic

	column COD_CENTRO_CUSTO
		dataType: string
		lineageTag: 574be6e7-f4ed-49ad-aa38-1a147c312168
		summarizeBy: none
		sourceColumn: COD_CENTRO_CUSTO

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: a9299216-295d-43e5-98d6-4dc0f21c07f6
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL
		dataType: double
		lineageTag: 1bd74c24-581a-439d-bfef-f4307efe0313
		summarizeBy: sum
		sourceColumn: TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CONTA_CONTABIL
		dataType: string
		lineageTag: d61406c7-c9ab-4848-9d42-76a8df930f08
		summarizeBy: none
		sourceColumn: CONTA_CONTABIL

		annotation SummarizationSetBy = Automatic

	column VALOR = IF(RELATED(dPlanoContas[TIPO]) = "-", ABS(fOrcProjecaoFinEstorno500[TOTAL]) * -1, ABS(fOrcProjecaoFinEstorno500[TOTAL]))
		lineageTag: f8d84c97-8684-476c-8d3e-2b37cd64ad40
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fOrcProjecaoFinEstorno500 = m
		mode: import
		source = ```
				let
				    Fonte = fOrcadoProjecao500,
				    #"Colunas Renomeadas" = Table.RenameColumns(Fonte,{{"CONTA_CONTABIL", "CONTA"}, {"VALOR", "TOTAL"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "CONTA_CONTABIL", each if Text.Start([CONTA],5) = "3.1.2" then 
				"9.9.9.9.99.02- ESTORNO RECEITAS FINANCEIRAS" else
				if Text.Start([CONTA],5) = "5.1.3" then
				"9.9.9.9.99.01- ESTORNO DESPESAS FINANCEIRAS" else
				[CONTA]),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada", each ([CONTA_CONTABIL] = "9.9.9.9.99.01- ESTORNO DESPESAS FINANCEIRAS" or [CONTA_CONTABIL] = "9.9.9.9.99.02- ESTORNO RECEITAS FINANCEIRAS")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"CONTA"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"CONTA_CONTABIL", type text}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

