table fOrcFinEstorno
	lineageTag: 7ec3b188-a1b8-410d-9e08-0fcac61fdc4e

	column COD_CASA
		dataType: string
		lineageTag: 64b147ce-7f15-49ce-a3bf-42f81e95bca5
		summarizeBy: none
		sourceColumn: COD_CASA

		annotation SummarizationSetBy = Automatic

	column COD_CENTRO_CUSTO
		dataType: string
		lineageTag: f0684ba5-3eba-4e34-9784-0b1a77d5544d
		summarizeBy: none
		sourceColumn: COD_CENTRO_CUSTO

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4e81a63f-6e08-417f-9d4a-7e7176fc9f2c
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL
		dataType: double
		lineageTag: c9a67ad6-9c24-460b-9cf0-10e4e77ee64d
		summarizeBy: sum
		sourceColumn: TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CONTA_CONTABIL
		dataType: string
		lineageTag: 02dc35f8-b3e6-4f78-b9ec-c79cb467e873
		summarizeBy: none
		sourceColumn: CONTA_CONTABIL

		annotation SummarizationSetBy = Automatic

	column VALOR = IF(RELATED(dPlanoContas[TIPO]) = "-", ABS(fOrcFinEstorno[TOTAL]) * -1, ABS(fOrcFinEstorno[TOTAL]))
		lineageTag: 1cfa3c77-7e26-45d3-81d3-9148837c8f13
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fOrcFinEstorno-a39a9909-db56-469a-828c-3a137d483e4c = m
		mode: import
		source = ```
				let
				    Fonte = fOrcado,
				    #"Colunas Renomeadas" = Table.RenameColumns(Fonte,{{"CONTA_CONTABIL", "CONTA"}, {"VALOR", "TOTAL"}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Colunas Renomeadas", "CONTA_CONTABIL", each if Text.Start([CONTA],5) = "3.1.2" then 
				"9.9.9.9.99.02- ESTORNO RECEITAS FINANCEIRAS" else
				if Text.Start([CONTA],5) = "5.1.3" then
				"9.9.9.9.99.01- ESTORNO DESPESAS FINANCEIRAS" else
				[CONTA]),
				    #"Linhas Filtradas" = Table.SelectRows(#"Personalização Adicionada", each ([CONTA_CONTABIL] = "9.9.9.9.99.01- ESTORNO DESPESAS FINANCEIRAS" or [CONTA_CONTABIL] = "9.9.9.9.99.02- ESTORNO RECEITAS FINANCEIRAS")),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"CONTA"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"CONTA_CONTABIL", type text}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

